apiVersion: app/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myc1
        image: nginx 