apiVersion: v1
kind: ReplicationController
metadata:
  name: sanjay_rc
spec:
  replicas: 3
  selector:
    app: mynginx
  template:
    metadata:
      name: mynginx
      labels:
        app: mynginx
    spec:
      containers:
        - name: myc1_san
          image: nginx
          ports:
            - containerPort: 80
