apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: first-rs
spec:
 replicas: 5
 selector:
   matchLabels:
     app: myapp
template:
  metadata:
    labels:
      app: myapp
  spec:
   containers:
     name: c1
     image: nginx    